spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tQGwqa9Aoo1wQEey7iQ
      secret-key: K0cmhle8E0HzPgpw7hNR8IrmlVgSIe
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: mall-ljl
      mysms:
        region-id: cn-hangzhou
        access-key-id: LTAI4G9GNwxYQ5mgDQWpDLiv
        secret: 8nNOjdtsiPH0fI5Kkr3XBooPr3WUN0
        sign-name: 李哥说Java
        template-code: SMS_195861786
  application:
    name: mall-third-party
  redis:
    host: 192.168.190.141
    port: 6379
    password: root
server:
  port: 40000
logging:
  level:
    com.learn.mall: debug
    com.alibaba.nacos.client.naming: WARN
    com.alibaba.nacos.client.config.impl: WARN


