spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: your access-key
      secret-key: your secret-key
      oss:
        endpoint: your endpoint
        bucket: your bucket
      mysms:
        region-id: cn-hangzhou
        access-key-id: your access-key-id
        secret: your secret
        sign-name: 李哥说Java
        template-code: SMS_195861786
  application:
    name: mall-third-party
  redis:
    host: 192.168.190.132
    port: 6379
server:
  port: 30000



